//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthITUnivApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class College
    {
        public int CollegeID { get; set; }
        public string CollegeName { get; set; }
        public string CollegeAbbrevation { get; set; }
        public string CollegeURL { get; set; }
        public string CollegeAddress { get; set; }
        public string CollegePhoneNo { get; set; }
        public string CollegeHead { get; set; }
        public string UniversityName { get; set; }
    }
}
