//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthITUnivApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentAbbreviation { get; set; }
        public string DepartmentURL { get; set; }
        public string DepartmentAddress { get; set; }
        public string DepartmentPhoneNo { get; set; }
        public string DepartmentHead { get; set; }
        public string CollegeName { get; set; }
    }
}
