//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthITUnivApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationSystem
    {
        public int SystemID { get; set; }
        public string SystemName { get; set; }
        public string SystemAbbreviation { get; set; }
        public string SystemURL { get; set; }
        public string SystemAddress { get; set; }
        public string SystemPhoneNo { get; set; }
        public string SystemHeadPerson { get; set; }
    }
}
