//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthITUnivApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonID { get; set; }
        public string PersonName { get; set; }
        public string PersonTitle { get; set; }
        public string PersonRole { get; set; }
        public string PersonType { get; set; }
        public string PersonPhoneNo { get; set; }
        public string PersonEmailID { get; set; }
        public string PersonStreet { get; set; }
        public string PersonCity { get; set; }
        public string PersonState { get; set; }
        public string PersonCountry { get; set; }
        public string PersonZipCode { get; set; }
        public string UniversityName { get; set; }
        public string CollegeName { get; set; }
        public string DepartmentName { get; set; }
    }
}
