//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthITUnivApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public int ProgramID { get; set; }
        public string ProgramName { get; set; }
        public string ProgramType { get; set; }
        public string DepartmentName { get; set; }
        public string ProgramLeadDepartment { get; set; }
        public string ProgramAbbrevation { get; set; }
        public string ProgramURL { get; set; }
        public string ProgramHead { get; set; }
    }
}
