//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthITUnivApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class University
    {
        public int UniversityID { get; set; }

        [Required(ErrorMessage = "Please enter UniversityName")]
        public string UniversityName { get; set; }

        [Required(ErrorMessage = "Please enter University Abbreviation")]
        public string UniversityAbbreviation { get; set; }
        public string UniversityURL { get; set; }
        public string UniversityStreet { get; set; }
        public string UniversityCity { get; set; }
        public string UniversityState { get; set; }
        public string UniversityCountry { get; set; }
        public string UniversityZipCode { get; set; }
        public string UniversityPhoneNo { get; set; }
        public string UniversityHead { get; set; }
        public string SystemName { get; set; }
    }
}
